name: Python Build Artifacts

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

env:
    PIP_INDEX_URL: "https://:2022-09-14T00:00:00.000000Z@time-machines-pypi.sealsecurity.io/"

jobs:
  maynlinux:
    name: Build Python artifacts on ubuntu-latest - ${{ matrix.artifact_name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - build_script: kokoro/linux/python36/build.sh
            artifact_name: python36
          - build_script: kokoro/linux/python36_cpp/build.sh
            artifact_name: python36_cpp
          - build_script: kokoro/linux/python37/build.sh
            artifact_name: python37
          - build_script: kokoro/linux/python37_cpp/build.sh
            artifact_name: python37_cpp
          - build_script: kokoro/linux/python38/build.sh
            artifact_name: python38
          - build_script: kokoro/linux/python38_cpp/build.sh
            artifact_name: python38_cpp
          - build_script: kokoro/linux/python39/build.sh
            artifact_name: python39
          - build_script: kokoro/linux/python39_cpp/build.sh
            artifact_name: python39_cpp
          - build_script: kokoro/linux/python310/build.sh
            artifact_name: python310
          - build_script: kokoro/linux/python310_cpp/build.sh
            artifact_name: python310_cpp
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run build script
        run: |
            bash ${{ matrix.build_script }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels-${{ runner.os }}-${{ matrix.artifact_name }}
          path: artifacts
  # macos:
  #   name: Build Python artifacts on macos
  #   runs-on: macos-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       include:
  #         - python-version: 3.6
  #           url: https://www.python.org/ftp/python/3.6.8/python-3.6.8-macosx10.9.pkg
  #         - python-version: 3.7
  #           url: https://www.python.org/ftp/python/3.7.1/python-3.7.1-macosx10.9.pkg
  #         - python-version: 3.8
  #           url: https://www.python.org/ftp/python/3.8.0/python-3.8.0-macosx10.9.pkg
  #         - python-version: 3.9
  #           url: https://www.python.org/ftp/python/3.9.0/python-3.9.0-macosx10.9.pkg
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Setup python
  #       run: |
  #         curl ${{ matrix.url }} -o python.pkg
  #         sudo installer -pkg python.pkg -target /

  #     - name: Install dependencies
  #       run: |
  #         brew install autoconf automake libtool

  #     - name: Run build script (Bash)
  #       run: |
  #           ln -s $PYTHON_EXE `dirname $PYTHON_EXE`/python 
  #           $PYTHON_EXE -m pip install -U virtualenv pip wheel setuptools
  #           bash kokoro/release/python/macos/build_artifacts.sh
  #       env:
  #           MB_PYTHON_OSX_VER: ${{ matrix.python-version }}
  #           PYTHON_EXE: /Library/Frameworks/Python.framework/Versions/${{ matrix.python-version }}/bin/python3

  #     - name: Upload artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: python-wheels-${{ runner.os }}-${{ matrix.python-version }}
  #         path: artifacts
