name: Python Build Artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Python artifacts on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            script: kokoro/release/python/linux/build_artifacts.sh
            shell: bash
          - os: macos-latest
            script: kokoro/release/python/macos/build_artifacts.sh
            shell: bash
          - os: windows-latest
            script: kokoro/release/python/windows/build_artifacts.bat
            shell: cmd

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: git config --global core.autocrlf false
        shell: bash
        if: runner.os == 'Windows'

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf libtool pkg-config

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install autoconf automake libtool

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install 7zip -y

      - name: Run build script (Bash)
        if: matrix.shell == 'bash'
        run: bash ${{ matrix.script }}

      - name: Run build script (Windows)
        if: matrix.shell == 'cmd'
        run: ${{ matrix.script }}
        shell: cmd

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels-${{ runner.os }}-${{ runner.arch }}
          path: artifacts/
          if-no-files-found: warn

