name: Python Build Artifacts

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

env:
    PIP_INDEX_URL: "https://:2022-09-14T00:00:00.000000Z@time-machines-pypi.sealsecurity.io/"

jobs:
  maynlinux:
    name: Build Python artifacts on ${{ matrix.os }} - ${{ matrix.image }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            script: kokoro/release/python/linux/build_artifacts.sh
            image: quay.io/pypa/manylinux2014_x86_64:2021-09-27-ed30de0
            artifact_name: manylinux2014_x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: MatteoH2O1999/setup-python@v4
        with:
          python-version: '3.6' # Only used to run the build script
    
      - name: Run build script (Bash)
        run: |
            python3 -m venv .venv
            source .venv/bin/activate
            python -m pip install -U virtualenv
            bash ${{ matrix.script }}
        env:
            DOCKER_IMAGE: ${{ matrix.image }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels-${{ runner.os }}-${{ matrix.artifact_name }}
          path: artifacts
