name: Python Build Artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
    PIP_INDEX_URL: "https://:2022-09-14T00:00:00.000000Z@time-machines-pypi.sealsecurity.io/"

jobs:
  maynlinux:
    name: Build Python artifacts on ${{ matrix.os }} - ${{ matrix.container }}
    runs-on: ${{ matrix.os }}
    container: 
      image: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            script: kokoro/release/python/linux/build_artifacts.sh
            container: quay.io/pypa/manylinux2014_x86_64
        #   - os: macos-latest
        #     script: kokoro/release/python/macos/build_artifacts.sh
        #     shell: bash
        #   - os: windows-latest
        #     script: kokoro/release/python/windows/build_artifacts.bat
        #     shell: cmd

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
    
      - name: Run build script
        run: bash ${{ matrix.script }}


