name: Python Build Artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
    PIP_INDEX_URL: "https://:2022-09-14T00:00:00.000000Z@time-machines-pypi.sealsecurity.io/"

jobs:
  maynlinux:
    name: Build Python artifacts on ${{ matrix.os }} - ${{ matrix.container }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            script: kokoro/release/python/linux/build_artifacts.sh
        #   - os: macos-latest
        #     script: kokoro/release/python/macos/build_artifacts.sh
        #     shell: bash
        #   - os: windows-latest
        #     script: kokoro/release/python/windows/build_artifacts.bat
        #     shell: cmd

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: MatteoH2O1999/setup-python@v4
        with:
          python-version: '3.6'      
    
    #   - name: Install dependencies
    #     run: |
    #       # apt-get update
    #       # apt-get install -y build-essential autoconf libtool pkg-config
    #       python3 -m pip install -U virtualenv pip setuptools wheel

      - name: Run build script (Bash)
        run: |
            $PYTHON_EXE -m venv .venv
            source .venv/bin/activate
            python -m pip install -U virtualenv pip setuptools wheel
            bash ${{ matrix.script }}
        env:
            PYTHON_EXE: python3
            DOCKER_IMAGE: quay.io/pypa/manylinux2010_x86_64:2021-09-27-ed30de0

